### ISSUE TITLE
Password forgot logic

### ISSUE THREAD

**Issue by pozylon** [unchainedshop/storefront#3]
It should hide the forgot password form when forgot password is submitted and it should mention that a password reset e-mail has been sent

It should redirect to the account page when password has been changed. It currently does not work and if the password reset link is expired the error is not shown to the user. server-side errors should be displayed between submit and form fields.

**Comment by pozylon** [comment]
@Mikearaya Not good yet, after I have received the password reset link it does not work and does not show any error: 

https://dynoptic-template.unchained.wtf/reset-password?token=0e38ee14904a09cd474b54eb3cfc2ac7823ef12f3dc6db6561e1f079578042b2ca20a3be04b7fbfdd86a85

**Comment by pozylon** [comment]
Sorry one sec I think that was my fault...

**Comment by Mikearaya** [comment]
@pozylon
